modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "genesis_ad_astra"
version = "${version}"
displayName = "Genesis: Ad Astra"
authors = "G_Mungus"
description = '''
Integrates Ad Astra into Genesis
'''
logoFile = "assets/genesis_ad_astra/icon.png"

[[dependencies.genesis_ad_astra]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.genesis_ad_astra]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.genesis_ad_astra]]
modId = "genesis"
mandatory = true
versionRange = "[1.20.1-0.7.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.genesis_ad_astra]]
modId = "ad_astra"
mandatory = true
versionRange = "[1.15.0,)"
ordering = "NONE"
side = "BOTH"